### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [marquinoir/codepath-flix#2]
The following user stories are checked in the readme but **not fully shown in the GIF**. These user stories are only given partial points. Please record a new GIF and resubmit your assignment using the submit button in the course portal to get the full points for the user story.

- User sees an app icon on the home screen and a styled launch screen
- User can view and scroll through a list of movies now playing in theaters

**Comment by marquinoir** [comment]
-updated to see the app icon on the home screen(gif starts on the home page with a click on the app)
-scroll through list is now shown in gif

**Comment by marquinoir** [comment]
issues addressed
